export const MAIN_PAGE_ROUTE = '/'
export const ABOUT_ROUTE = '/about'
export const LAYOUT_ROUTE = '/layout'
export const GALLERY_ROUTE = '/gallery'
export const LOCATION_ROUTE = '/location'
export const INSTRUCTION_ROUTE = '/instruction'